self.m_x_array_temp     = complex(row[3])
            self.m_y_array_temp     = complex(row[4])
            self.m_z_array_temp     = float(row[5])
            self.n_up_array_temp    = float(row[0])
            self.n_down_array_temp  = float(row[1])
            self.n_flip_array_temp  = complex(row[2])

            self.plus_x_noflip_u_temp   = complex(row[6])
            self.plus_x_noflip_d_temp   = complex(row[7])
            self.minus_x_noflip_u_temp  = complex(row[8])
            self.minus_x_noflip_d_temp  = complex(row[9])
            self.plus_y_noflip_u_temp   = complex(row[10])
            self.plus_y_noflip_d_temp   = complex(row[11])
            self.minus_y_noflip_u_temp  = complex(row[12])
            self.minus_y_noflip_d_temp  = complex(row[13])

            self.plus_x_flip_ud_temp   = complex(row[14])
            self.plus_x_flip_du_temp   = complex(row[15])
            self.minus_x_flip_ud_temp  = complex(row[16])
            self.minus_x_flip_du_temp  = complex(row[17])
            self.plus_y_flip_ud_temp   = complex(row[18])
            self.plus_y_flip_du_temp   = complex(row[19])
            self.minus_y_flip_ud_temp  = complex(row[20])
            self.minus_y_flip_du_temp  = complex(row[21])